<a href="https://colab.research.google.com/github/thomastomy5/ML/blob/main/numpy_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
from numpy import array
data = [11, 22, 33, 44, 55]
print(data)
print(type(data))
# array of data
data = array(data)
print(data)
print(type(data))

[11, 22, 33, 44, 55]
<class 'list'>
[11 22 33 44 55]
<class 'numpy.ndarray'>


In [12]:
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
print(data)
print(type(data))
# array of data
data = array(data)
print(data)
print(type(data))
print(data[0,1])

[[11, 22], [33, 44], [55, 66]]
<class 'list'>
[[11 22]
 [33 44]
 [55 66]]
<class 'numpy.ndarray'>
22


In [15]:
data = array([[11, 22, 33],
		[44, 55, 66],
		[77, 88, 99]])
# separate data
X, y = data[:, :-1], data[:, -1]
print(X)
print(y)

[[11 22]
 [44 55]
 [77 88]]
[33 66 99]


In [18]:
from numpy import reshape
# define array
data = array([11, 22, 33, 44, 55, 77])
print(data.shape)
# reshape
data = data.reshape(3, 2)
print(data.shape)
print(data)

(6,)
(3, 2)
[[11 22]
 [33 44]
 [55 77]]


In [19]:
# list of data
data = [[11, 22],
		[33, 44],
		[55, 66]]
# array of data
data = array(data)
print(data.shape)
# reshape
data = data.reshape((data.shape[0], data.shape[1], 1))
print(data.shape)
print(data)

(3, 2)
(3, 2, 1)
[[[11]
  [22]]

 [[33]
  [44]]

 [[55]
  [66]]]
